version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo install docker daemon
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - IMAGE_URI="${REPOSITORY_URI}:latest"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image for Pharma-approval backend...         
      - docker build -t ${REPOSITORY} -f pharma-approval/Dockerfile .
      - docker tag "${REPOSITORY}:latest" "$IMAGE_URI"      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image for Pharma-approval backend...
      - docker push "$IMAGE_URI"
      - printf '[{"name":"pharma-backend","imageUri":"%s"}]' "$IMAGE_URI" > pharma-approval/pharma_images.json
artifacts:
  files: pharma-approval/pharma_images.json
